from .DigitalFormGQLModel import DigitalFormGQLModel, DigitalFormQuery, DigitalFormMutation
from .DigitalFormSectionGQLModel import DigitalFormSectionGQLModel, DigitalFormSectionQuery, DigitalFormSectionMutation
from .DigitalSubmissionGQLModel import DigitalSubmissionQuery, DigitalSubmissionMutation, DigitalSubmissionGQLModel