mutation digitalFormSectionInsert($name: String, $nameEn: String, $sectionId: UUID, $formId: UUID!, $id: UUID, $fields: [DigitalFormFieldInsertGQLModel!], $sections: [DigitalFormSectionInsertGQLModel!]) {
  digitalFormSectionInsert(digitalFormSection: {name: $name, nameEn: $nameEn, sectionId: $sectionId, formId: $formId, id: $id, fields: $fields, sections: $sections}) {
    ... on DigitalFormSectionGQLModel { ...DigitalFormSection }
    ... on InsertError { ...InsertError }
  }
}

fragment User on UserGQLModel {
    __typename
    id
    }

fragment RBACObject on RBACObjectGQLModel {
    __typename
    id
    }

fragment DigitalFormField on DigitalFormFieldGQLModel {
    __typename
    id
    lastchange
    created
    createdbyId
    changedbyId
    rbacobjectId
    createdby { __typename }
    changedby { __typename }
    rbacobject { __typename }
    name
    label
    labelEn
    description
    formSectionId
    formSection { __typename }
    formId
    form { __typename }
    required
    order
    computed
    formula
    typeId
    backendFormula
    flattenFormula
    }

fragment DigitalFormSection on DigitalFormSectionGQLModel {
  __typename
  id
  lastchange
  created
  createdbyId
  changedbyId
  rbacobjectId
  createdby {
  ...User
}
  changedby {
  ...User
}
  rbacobject {
  ...RBACObject
}
  name
  path
  label
  labelEn
  description
  parentId
  sections { __typename }
  fields {
  ...DigitalFormField
}
  order
  repatableMin
  repatableMax
  repeatable
  parent {
        ... on DigitalFormSectionGQLModel { __typename id } # ... on DigitalFormSectionGQLModel { ...DigitalFormSection }
        ... on DigitalFormGQLModel { __typename id } # ... on DigitalFormGQLModel { ...DigitalForm }
      }
  }

fragment InsertError on InsertError {
  __typename
  msg
  failed
  input
  }
