import dataclasses
import datetime
from typing import Optional, List
from sqlalchemy import (
    Column,
    String,
    Integer,
    DateTime,
    ForeignKey,
)
from sqlalchemy.orm import Mapped, mapped_column

from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import relationship

from .BaseModel import BaseModel, UUIDColumn, UUIDFKey, IDType
###########################################################################################################################
#
# zde definujte sve SQLAlchemy modely
# je-li treba, muzete definovat modely obsahujici jen id polozku, na ktere se budete odkazovat
#
###########################################################################################################################

class DigitalSubmissionSectionModel(BaseModel):
    __tablename__ = "digital_submission_sections"

    path: Mapped[Optional[str]] = mapped_column(String, default=None, nullable=True)
    index: Mapped[Optional[int]] = mapped_column(Integer, default=None, nullable=True)
    # This column stores the parent section's id.
    section_id: Mapped[Optional[IDType]] = mapped_column(ForeignKey("digital_submission_sections.id"), default=None, nullable=True)
    # This column references the submission owning this section.
    submission_id: Mapped[Optional[IDType]] = mapped_column(ForeignKey("digital_submissions.id"), default=None, nullable=True)
    form_section_id: Mapped[Optional[IDType]] = mapped_column(ForeignKey("digital_form_sections.id"), default=None, nullable=True)
    state_id: Mapped[Optional[IDType]] = UUIDFKey(ForeignKey("states.id"), default=None, nullable=True)

    # Parent relationship (corresponds to the GraphQL field "section").
    form_section = relationship(
        "DigitalFormSectionModel",
        # remote_side="DigitalSubmissionSectionModel.id",
        # back_populates="child_sections",
        viewonly=True,
        uselist=False
    )

    section = relationship(
        "DigitalSubmissionSectionModel",
        remote_side="DigitalSubmissionSectionModel.id",
        back_populates="child_sections",
        uselist=False
    )

    # Child sections relationship (corresponds to the GraphQL field "sections").
    # child_sections = relationship(
    #     "DigitalSubmissionSectionModel",
    #     default_factory=list,
    #     init=True,
    #     back_populates="section",
    #     # viewonly=True,
    #     cascade="save-update",
    #     # lazy="select"
    #     # lazy="noload"
    # )

    # child_sections: List["DigitalSubmissionSectionModel"] = dataclasses.field(
    #     default_factory=list,
    #     init=True,
    #     metadata={"sa": relationship(
    #         "DigitalSubmissionSectionModel",
    #         back_populates="section",
    #         cascade="save-update",
    #         lazy="noload"
    #     )}
    # )

    child_sections = relationship(
        "DigitalSubmissionSectionModel",
        back_populates="section",
        cascade="save-update",
        # init=True,
        lazy="noload",
        collection_class=list
        # You can also specify a default factory if needed,
        # but in many cases SQLAlchemy will automatically initialize collection attributes.
    )    

    # Relationship to the submission owning this section.
    submission = relationship(
        "DigitalSubmissionModel",
        # back_populates="sections",
        viewonly=True,
        uselist=False
    )

    from .DigitalSubmissionFieldModel import DigitalSubmissionFieldModel
    # Relationship to the field (DigitalSubmissionFieldModel) associated with this section.
    fields = relationship(
        "DigitalSubmissionFieldModel",
        # default_factory=list,
        init=True,
        # back_populates="section",
        uselist=True,
        collection_class=list,
        cascade="save-update",
        # viewonly=True
    )

import uuid
from sqlalchemy import event, select

# @event.listens_for(DigitalSubmissionSectionModel, "before_insert")
def set_materialized_path(mapper, connection, target):
    """
    Before a new DigitalSubmissionSectionModel row is inserted,
    this event listener reads the parent's path (if any) and sets the 
    target's path accordingly.
    
    Note: For this to work, we must ensure that target.id is available.
    If the ID is normally generated by the database (e.g. autoincrement),
    you can instead generate a UUID (or another identifier) here.
    """
    # Ensure the record has an ID; if not, generate one.
    if not target.id:
        # Generate a UUID as a string (or use uuid.uuid4().int if your ID is an integer)
        target.id = str(uuid.uuid4())
    
    if target.section_id:
        # Retrieve the parent's path from the database.
        stmt = select(DigitalSubmissionSectionModel.path).where(
            DigitalSubmissionSectionModel.id == target.section_id
        )
        result = connection.execute(stmt)
        parent_path = result.scalar()
        # If parent's path is not set, fall back to using parent's ID.
        if parent_path is None:
            parent_path = str(target.section_id)
        # Set the new record's path as the parent's path + "/" + the new record's id.
        target.path = f"{parent_path}/{target.id}"
    else:
        # No parent: the path is simply the record's own id.
        target.path = str(target.id)